#!/usr/bin/env bash

function error_and_proceed() {
  errors+=("${1}")
  echo -e "tgenv: ${0}: Test Failed: ${1}" >&2
}

# https://dev.to/ifenna__/adding-colors-to-bash-scripts-48g4
RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
BLUE="\033[0;34m"
RESET="\033[0;39m"


function error_and_die() {
  if [[ "${TGENV_DISABLE_COLOR}" -eq 1 ]]; then
    echo -e "tgenv: $(basename "${0}"): [ERROR] ${1}" >&2
  else
    echo -e "tgenv: $(basename "${0}"): ${RED}[ERROR] ${1}${RESET}" >&2
  fi
  exit 1
}

function warn_and_continue() {
  if [ "${TGENV_DISABLE_COLOR}" -eq 1 ]; then
    echo -e "tgenv: $(basename "${0}"): [WARN] ${1}" >&2
  else
    echo -e "tgenv: $(basename "${0}"): ${YELLOW}[WARN] ${1}${RESET}" >&2
  fi
}

function info() {
  if [[ "${TGENV_DISABLE_COLOR}" -eq 1 ]]; then
    echo "[INFO] $1"
  else
    echo -e "${GREEN}[INFO] $1${RESET}"
  fi
}

function debug() {
  if [[ -n "${TGENV_DEBUG}" ]]; then
    if [[ "${TGENV_DISABLE_COLOR}" -eq 1 ]]; then
      echo -e "[DEBUG] ${1}"
    else
      echo -e "${BLUE}[DEBUG] ${1}${RESET}"
    fi
  fi
}

# Curl wrapper to switch TLS option for each OS
function curlw () {
  local TLS_OPT="--tlsv1.2"

  # Check if curl is 10.12.6 or above
  if [[ -n "$(command -v sw_vers 2>/dev/null)" && ("$(sw_vers)" =~ 10\.12\.([6-9]|[0-9]{2}) || "$(sw_vers)" =~ 10\.1[3-9]) ]]; then
    TLS_OPT=""
  fi

  curl ${TLS_OPT} "$@"
}
