#!/usr/bin/env bash

[ -n "${TGENV_DEBUG}" ] && set -x
source "${TGENV_ROOT}/libexec/helpers"

declare version_requested version regex

if [ -z "${1}" ]; then
  version_file="$(tgenv-version-file)"
  if [ "${version_file}" != "${TGENV_ROOT}/version" ]; then
    version_requested="$(cat "${version_file}" || true)"
  fi
else
  version_requested="${1}"
fi

if [[ "${version_requested}" =~ ^latest\:.*$ ]]; then
  version="${version_requested%%\:*}"
  regex="${version_requested##*\:}"
elif [[ "${version_requested}" =~ ^latest$ ]]; then
  version="${version_requested}"
  regex="^[0-9]\+\.[0-9]\+\.[0-9]\+$"
else
  version="${version_requested}"
  regex="^${version_requested}$"
fi

[ -d "${TGENV_ROOT}/versions" ] \
  || error_and_die "No versions of terragrunt installed. Please install one with: tgenv install"

version="$(\ls "${TGENV_ROOT}/versions" \
  | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3 \
  | grep -e "${regex}" \
  | head -n 1
)"

[ -n "${version}" ] || error_and_die "No installed versions of terragrunt matched '${version_requested}'"

target_path="${TGENV_ROOT}/versions/${version}"
[ -f "${target_path}/terragrunt" ] \
  || error_and_die "Version directory for ${version} is present, but the terragrunt binary is not! Manual intervention required."
[ -x "${target_path}/terragrunt" ] \
  || error_and_die "Version directory for ${version} is present, but the terragrunt binary is not executable! Manual intervention required. "

info "Switching to v${version}"
echo "${version}" > "$(tgenv-version-file)" || error_and_die "'switch to v${version} failed'"
terragrunt --version 1>/dev/null || error_and_die "'terragrunt --version' failed. Something is seriously wrong"
info "Switching completed"
