#!/usr/bin/env bash

[ -n "${TGENV_DEBUG}" ] && set -x
source "${TGENV_ROOT}/libexec/helpers"

echo "Checkout to mainstream branch"
echo ""

sleep 2

git checkout main

echo "Upgrade TGEnv to lastest version"

sleep 2

git pull

git log -1

exit 0
