#!/usr/bin/env bash

##########################################
#
# This script just works like a software
# version updater. It's a shortcut to
# $ git checkout master && git pull
#
##########################################

[ -n "${TGENV_DEBUG}" ] && set -x
source "${TGENV_ROOT}/libexec/helpers"

TGFD=$HOME/.tgenv
TGGB=$(git branch)
TGGM=$(git -C $TGFD checkout main)
TGGP=$(git pull)
TGGL=$(git -C $TGFD log -1)

# If branch it was different of main executes the checkout them
if [$TGGB != 'main']; 
then
   $TGGM
else
   $TGGP
fi;

echo $TGGL

exit 0
