#!/usr/bin/env bash

[ -n "${TGENV_DEBUG}" ] && set -x
source "${TGENV_ROOT}/libexec/helpers"

declare version_requested version regex

if [ -z "${1}" ]; then
  info "Version not specified, looking for version file"
  version_file="$(tgenv-version-file)"
  if [ "${version_file}" != "${TGENV_ROOT}/version" ]; then
    version_requested="$(cat "${version_file}" || true)"
  else
    info "Version file not found, using latest"
    version_requested="latest"
  fi
else
  version_requested="${1}"
fi

if [[ "${version_requested}" =~ ^latest\:.*$ ]]; then
  version="${version_requested%%\:*}"
  regex="${version_requested##*\:}"
elif [[ "${version_requested}" =~ ^latest$ ]]; then
  version="${version_requested}"
  regex="^[0-9]\+\.[0-9]\+\.[0-9]\+$"
else
  version="${version_requested}"
  regex="^${version_requested}$"
fi

version="$(\ls "${TGENV_ROOT}/versions" \
  | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3 \
  | grep -e "${regex}" \
  | head -n 1
)"

if [ -z "${version}" ]; then
  if [ "${TGENV_AUTO_INSTALL:-true}" == "true" ]; then
    info "version '${version_requested}' is not installed. Installing now as TGENV_AUTO_INSTALL==true"
    tgenv-install "${version_requested}"
    version="$(\ls "${TGENV_ROOT}/versions" \
      | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3 \
      | grep -e "${regex}" \
      | head -n 1
    )"
    [ -n "${version}" ] || error_and_die "Installation of '${version_requested}' succeeded but version not found afterwards"
  else
    error_and_die "No installed versions of terragrunt matched '${version_requested}'. Set TGENV_AUTO_INSTALL=true to install automatically or install one with: tgenv install"
  fi
fi

target_path="${TGENV_ROOT}/versions/${version}"
[ -f "${target_path}/terragrunt" ] \
  || error_and_die "Version directory for ${version} is present, but the terragrunt binary is not! Manual intervention required."
[ -x "${target_path}/terragrunt" ] \
  || error_and_die "Version directory for ${version} is present, but the terragrunt binary is not executable! Manual intervention required. "

info "Switching to v${version}"
echo "${version}" > "$(tgenv-version-file)" || error_and_die "'switch to v${version} failed'"
terragrunt --version 1>/dev/null || error_and_die "'terragrunt --version' failed. Something is seriously wrong"
info "Switching completed"
