#!/usr/bin/env bash

##########################################
# This script just works like a software
# version updater. It's a shortcut to
# $ git checkout main && git pull
##########################################

set -e
[ -n "${TGENV_DEBUG}" ] && set -x
INITIAL_DIR=$(pwd)
source "${TGENV_ROOT}/libexec/helpers"

debug "Changing directory to ${TGENV_ROOT}"
cd "${TGENV_ROOT}"

info "Stashing any changes and checking out main branch. Uncommitted changes can be restored after the update with 'git stash apply'"

# NOTE(simonm) stash and checkout are idempotent so the simplest option is to
# do these operations every time.
git stash
git checkout main
git pull
git log -1

debug "Changing directory to ${INITIAL_DIR}"
cd "${INITIAL_DIR}"

