name: 'Test'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  test-pull-requests-docker:
    # if: github.event_name == 'pull_request'
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    container: "${{ matrix.image }}"
    strategy:
      matrix:
        image:
          - 'alpine:latest'
          - 'ubuntu:latest'
          - 'fedora:latest'
    steps:
      - uses: 'actions/checkout@v2'
        with:
          fetch-depth: 1
      - name: 'Setup runner'
        run: './test/setup_runner.sh'
      - name: 'Install Dependencies'
        run: './test/install_deps.sh'
      - name: 'Run all tests'
        run: './test/run.sh'
        shell: 'bash'

  test-pull-requests-non-docker:
    # if: github.event_name == 'pull_request'
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - 'macos-latest'
          # - 'windows-latest'
    steps:
      - uses: 'actions/checkout@v2'
        with:
          fetch-depth: 1
      - name: 'Setup runner'
        run: './test/setup_runner.sh'
      - name: 'Install Dependencies'
        run: './test/install_deps.sh'
      - name: 'Run all tests'
        run: './test/run.sh'
        shell: 'bash'

#  # Only checking latest Linux/UNIX on pulls to save execution times
#   test-main-pulls:
#     if: github.event_name == 'pull_request'
#     runs-on: "${{ matrix.os }}"
#     strategy:
#       matrix:
#         os:
#           - 'macos-latest'
#           - 'windows-latest'
#     steps:
#       - uses: 'actions/checkout@v2'
#         with:
#           fetch-depth: 1
#       - name: 'Install Dependencies'
#         run: './test/install_deps.sh'
#       - name: 'Run all tests'
#         run: './test/run.sh'
#         shell: 'bash'

  # # When we push to main, test everything in order to guarantee releases
  # test-main-pushes:
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   runs-on: "${{ matrix.os }}"
  #   strategy:
  #     matrix:
  #       os:
  #         - 'macos-latest'
  #         - 'ubuntu-latest'
  #   steps:
  #     - uses: 'actions/checkout@v2'
  #       with:
  #         fetch-depth: 1

  #     - name: 'Install Dependencies'
  #       run: './test/install_deps.sh'

  #     - name: 'Run all tests'
  #       run: './test/run.sh'
  #       shell: 'bash'
